/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const HighScore = IDL.Record({
  'player' : IDL.Principal,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'getBestScore' : IDL.Func([], [HighScore], ['query']),
  'getGlobalLeaderboard' : IDL.Func([IDL.Nat], [IDL.Vec(HighScore)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const HighScore = IDL.Record({
    'player' : IDL.Principal,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    'getBestScore' : IDL.Func([], [HighScore], ['query']),
    'getGlobalLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(HighScore)],
        ['query'],
      ),
    'submitScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };